### ISSUE TITLE
Add in code audio 

### ISSUE THREAD

**Issue by soldadocoder** [Kailash-Natarajan/Raspberry-Pi-Camera-Video-Streaming-60-FPS-HTTP#1]
Hello my friend. I really liked your project. Sorry for the weird English. I'm Brazilian and I'm still learning English. I still use Google Translate to communicate. I wanted to know about the system, is it possible to insert the code to transmit the audio together or just the video? I have an HDMI video and audio capture card. I want to use your code to do this. Thank you very much.

**Comment by Kailash-Natarajan** [comment]
Hello. Could you please clarify your question. 

This repo is regarding the streaming of video feed captured from a camera on Raspberry Pi over Wi-Fi/LAN. You have mentioned "HDMI video and audio capture card". Does that mean you are trying to connect a multimedia device to your PC using USB. If so, then, both are completely unrelated. Although for HDMI capture card, you can try using OBS.
